#!/bin/sh
# Builds the web version: web/starfield.wasm, web/wasm.js (the same bytes as
# base64, so bundlers needn't find a .wasm file), and web/presets.js. All
# three are committed, so installing from GitHub needs no build.
# Needs zig (https://ziglang.org, or brew install zig) and node.
set -eu
cd "$(dirname "$0")/.."

zig cc -target wasm32-wasi -Oz -s -mexec-model=reactor -I core web/bridge.c core/starfield.c -o web/starfield.wasm
node -e '
  const fs = require("fs");
  const b64 = fs.readFileSync("web/starfield.wasm").toString("base64");
  fs.writeFileSync("web/wasm.js", "// Generated by web/build.sh from web/starfield.wasm. Don\x27t edit.\nexport default \"" + b64 + "\";\n");
'
node web/gen-presets.mjs
echo "Built web/starfield.wasm ($(wc -c < web/starfield.wasm | tr -d " ") bytes), web/wasm.js, web/presets.js"
